### PR TITLE
Support snakeviz

### PR DESCRIPTION
**Pull request by mdboom**
Implements half of what is suggested in #183.  This adds `snakeviz` as a new profiling gui type.

Also fixes a couple of buglets with the profiling command.

@cdeil, @jiffyclub

### CODE REVIEW

**Comment by cdeil** [comment]
The first profile command I tried was the one from the docs ... it fails with a "bad marshal data" error because it's trying to open a Python 2.7 profile with Python 3.4:
https://gist.github.com/cdeil/a90ea9106fc06ec9e7e9

**Comment by cdeil** [comment]
Now I'm getting this `KeyError`:
```
eduroam-3-163:gammapy-benchmarks deil$ asv profile time_FluxDistribution v0.1 --python 3.4 
· Discovering benchmarks
·· Creating virtualenv for py3.4-astropy-numpy-scipy..
·· Uninstalling gammapy from py3.4-astropy-numpy-scipy.
·· Installing gammapy into py3.4-astropy-numpy-scipy....
· Profile data does not already exist. Running profiler now.
·· Creating virtualenv for py3.4-astropy-numpy-scipy..
·· Uninstalling gammapy from py3.4-astropy-numpy-scipy.
·· Installing gammapy into py3.4-astropy-numpy-scipy...
·· Benchmarking py3.4-astropy-numpy-scipy
··· Running time_catalog.time_FluxDistribution                                                                                             65.78msTraceback (most recent call last):
  File "/Users/deil/Library/Python/3.4/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1', 'console_scripts', 'asv')()
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/asv-0.1-py3.4.egg/asv/main.py", line 36, in main
    result = args.func(args)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/asv-0.1-py3.4.egg/asv/commands/__init__.py", line 45, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/asv-0.1-py3.4.egg/asv/commands/profiling.py", line 107, in run_from_conf_args
    environment=args.environment, python=args.python)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/asv-0.1-py3.4.egg/asv/commands/profiling.py", line 206, in run
    profile_data = results[benchmark]['profile']
KeyError: 'time_FluxDistribution'
```

**Comment by mdboom** [comment]
> The first profile command I tried was the one from the docs ... it fails with a "bad marshal data" error because it's trying to open a Python 2.7 profile with Python 3.4.

Not sure how to fix that one, but we should document it.  I haven't run into this because I've been doing profiling in the same version of Python that I have runsnake and snakeviz installed for.  I suppose what we have to do is save it in some cross-Python compatible way (if that's even easy to do) and then convert it back to the correct version before passing along to the GUI tool (which means we have to know what version of Python it expects etc.).  Ugh.

> Now I'm getting this KeyError:

For some reason the profiling is failing, but the traceback is not being displayed.  I'll have to poke at this a bit to see if I can reproduce it.

**Comment by cdeil** [comment]
For the Py 2/3 profile issue ... how about catching the error, printing a warning users will understand and go on ... in this case it would continue to do the profiling for Python 3 and display it like I want, no?

**Comment by mdboom** [comment]
There's two issues here (and I was confused about which one you were running into):

- The GUI we load the profiling in has to be the same version of Python that we ran the profiler in.  This one is hard to catch for, since it's difficult to know what version of Python the external GUI tool will run in.

- When the profiling results are just printed as a table to the console, we also have to make sure that the `asv` master process is the same version of Python as the slave benchmarking process.  This is at least something we can catch and control.

**Comment by mdboom** [comment]
This has been updated so:

- It will raise an exception when the master and slave Python versions don't match.  We have to assume that the Python versions of `asv` and the GUI tool do match.

- You get a proper error message when the benchmark name is not fully specified (as the docstring says).

**Comment by mdboom** [comment]
> Now I'm getting this KeyError:

This is because the benchmark name wasn't being fully specified (it's ambiguous without a full path).  This has been fixed so one gets an error message and not a traceback.

**Comment by cdeil** [comment]
This basically works ... here's some minor comments ...

Exiting `snakeviz` by closing the web browser tab results in this error:
```
· Error running /Users/deil/Library/Python/3.4/bin/snakeviz /var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/tmp7mp9h82s
            STDOUT -------->
            
            STDERR -------->
            
Traceback (most recent call last):
  File "/Users/deil/Library/Python/3.4/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1', 'console_scripts', 'asv')()
  File "/Users/deil/code/asv/asv/main.py", line 36, in main
    result = args.func(args)
  File "/Users/deil/code/asv/asv/commands/__init__.py", line 45, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/deil/code/asv/asv/commands/profiling.py", line 108, in run_from_conf_args
    environment=args.environment, python=args.python)
  File "/Users/deil/code/asv/asv/commands/profiling.py", line 217, in run
    return cls.guis[gui].open_profiler_gui(profile_path)
  File "/Users/deil/code/asv/asv/plugins/snakeviz.py", line 26, in open_profiler_gui
    return util.check_call([command, profiler_file])
  File "/Users/deil/code/asv/asv/util.py", line 219, in check_call
    dots=dots, display_error=display_error, shell=shell, env=env)
  File "/Users/deil/code/asv/asv/util.py", line 330, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/Users/deil/Library/Python/3.4/bin/snakeviz /var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/tmp7mp9h82s' returned non-zero exit status -15
```
Maybe special-case this exit code as normal and don't raise this error?

When I select a benchmark that doesn't exist I get the correct message, but should `asv` create a virtualenv and uninstall / install the project in this case?
```
$ asv profile me_no_exit v0.1 --python 3.4 -g snakeviz
· Discovering benchmarks
·· Creating virtualenv for py3.4-astropy-numpy-scipy..
·· Uninstalling gammapy from py3.4-astropy-numpy-scipy.
·· Installing gammapy into py3.4-astropy-numpy-scipy....
· Could not find benchmark me_no_exit
```

**Comment by mdboom** [comment]
> Maybe special-case this exit code as normal and don't raise this error?

That makes sense.

> When I select a benchmark that doesn't exist I get the correct message, but should asv create a virtualenv and uninstall / install the project in this case?

Yes -- `asv` needs to install the benchmarked project into an environment in order to discover the benchmarks that are available.  So you can't determine if a benchmark exists until you've done that.

**Pull request merged**
