### PR TITLE
DOC: comment out not implemented but logical to have teardown_cache

### LINKED ISSUE #511: teardown_cache is "exampled" but not implemented
#277 added support for `setup_cache` and I see example also of the matching `teardown_cache` in test/benchmark/cache_examples.py but unfortunately support for it is actually not implemented. So if I am creating some reusable by all benchmarks resource (e.g. temporary file), the only way I could get rid of it whenever I am done I guess is to use atexit callback

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #511

### CODE REVIEW

**Comment by pv** [comment]
I think you can probably remove the function instead, it is probaly 
leftover from an earlier design.

**Comment by yarikoptic** [comment]
it was more of a hint that may be it is worth implementing it eventually ? ;)  e.g. to fulfill the cases beyond temp file in cwd (establish DB, start some docker container, etc)

**Comment by pv** [comment]
Yes, it could possibly be useful for such external state control. 
Doctrine however forbids commented-out code :)

**Comment by yarikoptic** [comment]
ok - here you go

**Comment by pv** [comment]
thanks, merged (busy times...).

**Pull request merged**
