### PR TITLE
Support for named benchmarks

### PR DESCRIPTION
**Pull request by philpep**
Related to #481

### CODE REVIEW

**Comment by pv** [comment]
I guess this is mostly OK. Comments:

- I think the attribute name should be the more specific `benchmark_name` instead of `name`
- The benchmark selection now needs to import the whole benchmark suite for each benchmark run, which may be expensive. Would it make sense in `get_benchmark_from_name` to first try importing the benchmark function based on its name, and only if that fails fall back to scrounging with `disc_benchmarks`?

**Comment by philpep** [comment]
Sorry for the delay.

Pushed new commits with ``benchmark_name`` attribute instead of ``name``.

The current implementation of benchmark discovery by name use a generator, so it doesn't always import the whole suite. Nevertheless I re-implemented direct import of benchmark in https://github.com/spacetelescope/asv/pull/484/commits/9fb848ed0796a2cccd0924e4dff2f2e8ff85f40a
I'd prefer to write it shorter but didn't find a way. My opinion is that this is not worth to have this complexity since import of the benchmark suite should be insignificant comparing to the benchmark run. Let me know if you prefer to drop it and I'll update the PR.

Thanks !

**Comment by pv** [comment]
The benchmark suite import time can be similar to the benchmark runtime. 
For example, for the scipy benchmark suite, it's 0.5 sec vs. ~0.1 sec 
per-file. For pandas, it's ~ 1.0 sec total vs. 0.3 sec per-file (both 
with hot disk cache here).

**Comment by pv** [comment]
Note that the 'benchmarks' package name should be replaced by dirname(root).

**Comment by philpep** [comment]
Good catch ! I updated the commit.

**Pull request merged**
