### PR TITLE
Automated regression detection

### PR DESCRIPTION
**Pull request by pv**
Here's some work on detecting and listing benchmark regressions automatically:
Sample output: https://pv.github.io/scipy-bench/#/regressions
http://pav.iki.fi/tmp/asv-236/

It works by fitting piecewise constant functions to all graphs, and using the result to determine the best value  and the date+commit where it regressed.

Fitting piecewise constant functions has exact solutions in `O(n^2)` time, for minimizing objective functions of the form `f = gamma * {#jumps in y_fit} + sum((y - y_fit)**p)` for p=1 or 2. With some reasonably sounding heuristics apparently good solutions can be found in linear time. The parameter gamma is picked by minimizing `beta {#jumps} ln(n)/n + log sum((y - y_fit)**p)` which apparently is some information criterion for gaussian models (no rigor is attempted, it seems to work reasonably with beta=3). 

For 2-norm, all this seems to work fast enough up to 50k+ commits. The 1-norm is approx 10x slower, as I didn't manage to optimize it better in pure Python.

- [x] Some more testing with real-world data could be useful.
- [x] Better unit tests for generated data
- [x] Maybe the plugin should be made optional?
- [x] The "regressions" web page was factored out of asv.js, making the setup more extensible. I didn't go all the way in factoring everything to pieces. Looks reasonably future-proof to me, but ymmv?
- [x] Not sure what's the best way of reporting the results, e.g., should it only report the most recent regression rather than comparing to the best value?
- [x] Preserve table sort if user presses back button
- [x] show commit ranges instead of commits
- [x] way to specify earliest commit to regress in asv.conf
- [x] deal properly with branches and multiple machines
- [x] way to ignore specific regressions
- [x] fine-tune step detection algorithm --- it's not fully satisfactory as of f33b30e, and tends to report spurious regressions at end of the time series

### CODE REVIEW

**Comment by mdboom** [comment]
This is really cool.

This assumes that all commits have been benchmarked, correct?  For example, on the astropy benchmarks (which you've kindly provided an example of), the commit link for the regressions is irrelevant because the commits are only subsampled.

It seems that ideally this search of the regression space would be combined with the `asv bisect` command to "dig down" and find the specific commits that are to blame.

**Comment by pv** [comment]
Yes, having the commit links assumes everything is benchmarked. It would be straightforward to display commit ranges instead of commits, if the regressing commit is ambiguous, or give e.g. copypasteable asv bisect command lines.

A different practical question is: a typical situation seems to be that somewhere in history the performance obtained its best value, and then regressed. After that, the regression was fixed (or something else happened), but it's still worse than the original value. What's the most useful way to report this?

The current way probably isn't too bad, although it would be useful to mark regressions as "known" to exclude them from the report, a bit similar to the suggested idea to add labels in gh-191

**Comment by mdboom** [comment]
> Yes, having the commit links assumes everything is benchmarked. It would be straightforward to display commit ranges instead of commits, if the regressing commit is ambiguous, or give e.g. copypasteable asv bisect command lines.

That sounds like a good compromise, and I think would avoid initial confusion.  Something that automatically runs git bisect based on a reasonable place to look can always be done as a follow-on.

> although it would be useful to mark regressions as "known" to exclude them from the report, a bit similar to the suggested idea to add labels in gh-191

Would a way of marking the "earliest" commit to report on (on a benchmark-by-benchmark basis) make sense for that?

**Comment by pv** [comment]
Ok, I think this PR is converging now. The performance seems reasonable even for the more robust 1-norm fitting, and false positive rate seems low enough. I'd rather waste a minute of computer time for analysis than wasting developer time for eyeballing squiggly lines. The UI now reports all detected "significant" breakpoints. The significance threshold in principle could be bumped up, but the false positive rate seems low enough currently, at least based on the astropy/scipy results linked to above.

After getting this work in practice, I also added some amateur-level statistical analysis arguments to the docs to get it work also in theory.

**Comment by mdboom** [comment]
This is cool.  It's too bad the ignore buttons use local storage (and thus other users viewing the same results will still see this) but I don't see a way around that without a server-side component.  Is there a way the ignore selections could be exported and then committed to the git repo containing the results?

**Comment by pv** [comment]
Yes, it could be useful to have the web frontend output something that
can just be copypasted to asv.conf.json. The main question here then are
(i) whether such builtin config should just hide the results by default
so that you can still unignore them, or, completely remove them, and
(ii) whether to put the config to asv.conf.json or some other config file.

**Comment by pv** [comment]
Ok, added a widget showing copypasteable config file excerpt for ignoring the currently ignored regressions.

The config file option limits the commit ranges considered in computation, so that it removes the regressions in question rather than just hiding them. I didn't want to have two ways of ignoring regressions in the config file, and since limiting computation might be required in some cases, I just went with that.

**Comment by mdboom** [comment]
> I didn't want to have two ways of ignoring regressions in the config file, and since limiting computation might be required in some cases, I went with that.

That makes sense.

**Comment by mdboom** [comment]
Sorry this has sat here for a while.  @pv: Good to merge in your opinion?  (Looks good to me).

**Comment by pv** [comment]
I think this has converged, and should be fairly usable currently. I don't have remaining TODO items currently.

I know there may be more robust change point detection algorithms in the literature, but within the constraints here (pure-Python, no special functions, must be fast) I think this is reasonable effort for the purpose.

**Comment by pv** [comment]
Ok, merging.

**Pull request merged**
