### PR TITLE
Use color_print for Unicode fallback

### LINKED ISSUE #317: BUG: in asv continuous on latest master
```
· Creating environments
· Discovering benchmarks
·· Uninstalling from py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt.
·· Building for py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt................................
·· Installing into py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt..
· Running 10 total benchmarks (2 commits * 1 environments * 5 benchmarks)
[  0.00%] · For pandas commit hash ab488b89:
[  0.00%] ·· Building for py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt................................
[  0.00%] ·· Benchmarking py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
[ 10.00%] ··· Running binary_ops.timestamp_tz_ops_diff1.time_timestamp_ops_diff1                                                                                                                                            179.33?s
[ 20.00%] ··· Running binary_ops.timestamp_tz_ops_diff2.time_timestamp_ops_diff2                                                                                                                                            247.17ms
[ 30.00%] ··· Running binary_ops.timestamp_tz_series_compare.time_timestamp_series_compare                                                                                                                                  208.09?s
[ 40.00%] ··· Running timeseries.dti_reset_index_tz.time_dti_reset_index_tz                                                                                                                                                 451.28?s
[ 50.00%] ··· Running timeseries.timeseries_timestamp_tzinfo_cons.time_timeseries_timestamp_tzinfo_cons                                                                                                                       8.37?s
[ 50.00%] · For pandas commit hash f82e1778:
[ 50.00%] ·· Building for py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt................................
[ 50.00%] ·· Benchmarking py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
[ 60.00%] ··· Running binary_ops.timestamp_tz_ops_diff1.time_timestamp_ops_diff1                                                                                                                                            159.14ms
[ 70.00%] ··· Running binary_ops.timestamp_tz_ops_diff2.time_timestamp_ops_diff2                                                                                                                                            157.42ms
[ 80.00%] ··· Running binary_ops.timestamp_tz_series_compare.time_timestamp_series_compare                                                                                                                                    1.59ms
[ 90.00%] ··· Running timeseries.dti_reset_index_tz.time_dti_reset_index_tz                                                                                                                                                   6.04ms
[100.00%] ··· Running timeseries.timeseries_timestamp_tzinfo_cons.time_timeseries_timestamp_tzinfo_cons                                                                                                                       8.46?s
BENCHMARK                                    BEFORE      AFTER     FACTOR
Traceback (most recent call last):
  File "/Users/jreback/miniconda/bin/asv", line 9, in <module>
    load_entry_point('asv==0.2.dev794+8819998b', 'console_scripts', 'asv')()
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/asv-0.2.dev794+8819998b-py2.7.egg/asv/main.py", line 36, in main
    result = args.func(args)
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/asv-0.2.dev794+8819998b-py2.7.egg/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/asv-0.2.dev794+8819998b-py2.7.egg/asv/commands/continuous.py", line 50, in run_from_conf_args
    show_stderr=args.show_stderr, bench=args.bench, machine=args.machine
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/asv-0.2.dev794+8819998b-py2.7.egg/asv/commands/continuous.py", line 141, in run
    before_display, after_display, change))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 60: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by mdboom**
Fixes #317

### CODE REVIEW

**Comment by pv** [comment]
gh-313 might also fix it

**Comment by mdboom** [comment]
It looks like #313 still has the same problem:

https://github.com/spacetelescope/asv/pull/313/files#diff-3687124b3d830a22fc57a2e224949d66R266

But I do see how it might be easier to just fix this on top of #313 than to merge the two.

**Comment by pv** [comment]
Those are just the commit hashes though, which shouldn't contain non-ascii.
The detail print below is done via color_print

**Comment by pv** [comment]
Travis is failing due to `test_compare` benchmark output changing.
Otherwise this looks good to me.

**Comment by mdboom** [comment]
I've merged #313.  I'm going to rebase this on that and fix test failures etc.

**Comment by pv** [comment]
Looks good to me, merged.

**Pull request merged**
