### PR TITLE
For python=same, do not clone repository or print no-op actions

### PR DESCRIPTION
**Pull request by pv**
The `asv dev` / `asv run --python=same` commands assume the project is already installed in the current overall Python environment. Therefore, we can skip all operations on the repository. Also, skip printing unnecessary things to stdout, and add a test checking `asv dev` works.

The use case I have in mind is to be able to use asv simply as a benchmark runner, without needing its repository/environment management features.

### CODE REVIEW

**Comment by mdboom** [comment]
This makes a lot of sense.  I wonder, however, if it might be better to have a new no-op subclass of `Repo` that goes into effect when `python=='same'` (much like `ExistingEnvironment` is a mostly no-op implementaton of `Environment`).  That would take all of these changes to not touch the repo out of the many places they are used and into the `repo.py` module.

**Comment by pv** [comment]
Yes, that will probably cover the cases needed here, and more in case future commands will also need this.

**Comment by pv** [comment]
Ok, this should be more sensible now.

**Comment by mdboom** [comment]
Looks good.  Thanks!

**Pull request merged**
