### PR TITLE
Make timeouts also on Windows based on last output timestamp

### PR DESCRIPTION
**Pull request by pv**
I don't have a Windows machine at hand (only WINE), so this isn't fully tested, but should work.

Fixes gh-319

cc @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Yes, this seems to work!

**Comment by mdboom** [comment]
Makes sense to me (though I don't have Windows to test on, either)

**Comment by pv** [comment]
Probably safe to merge, seems simple in principle.

**Comment by seth-p** [comment]
FYI, using the latest code from master (0.2.dev818+c07fdbf2) I get a timeout after a bit under 4 minutes when running the Pandas asv tests (64-bit Python 3.4.3 on Windows 7). https://github.com/pydata/pandas/pull/9023#issuecomment-148934789

**Comment by pv** [comment]
Perhaps the compilation of `algos.c` just takes more than 120 seconds --- can probably be checked by running the command shown in the log manually?

However, 2 min timeout is probably too short for compilation, and it's not handled correctly anyway (asv quits with error rather than dealing with it).

**Comment by seth-p** [comment]
Perhaps one should be able to specify/override the timeouts (I recall seeing them in three places in the code) on the command line and/or confit file?

**Pull request merged**
